// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvuucrJIg9fn5Xa0veveha5iODnaTHFSM',
    appId: '1:726202907790:web:046b17ee8f7f207b369ddf',
    messagingSenderId: '726202907790',
    projectId: 'mediconnect2-6fb51',
    authDomain: 'mediconnect2-6fb51.firebaseapp.com',
    storageBucket: 'mediconnect2-6fb51.appspot.com',
    measurementId: 'G-4T8MLSRGP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCacIoJK0_6Nwn3OCCf4mH7Nd_5SgYaTF4',
    appId: '1:726202907790:android:059fc091fcabf5f5369ddf',
    messagingSenderId: '726202907790',
    projectId: 'mediconnect2-6fb51',
    storageBucket: 'mediconnect2-6fb51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhRol44LR9yTTvfZ-rvq-ZkxqFsbuvJ-o',
    appId: '1:726202907790:ios:a976d4fb1b174a83369ddf',
    messagingSenderId: '726202907790',
    projectId: 'mediconnect2-6fb51',
    storageBucket: 'mediconnect2-6fb51.appspot.com',
    iosBundleId: 'com.example.mediconnect2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhRol44LR9yTTvfZ-rvq-ZkxqFsbuvJ-o',
    appId: '1:726202907790:ios:fe659042681e70e8369ddf',
    messagingSenderId: '726202907790',
    projectId: 'mediconnect2-6fb51',
    storageBucket: 'mediconnect2-6fb51.appspot.com',
    iosBundleId: 'com.example.mediconnect2.RunnerTests',
  );
}
